sudo: false
dist: trusty
group: stable

language: java

jdk:
  - oraclejdk8

notifications:
  email:
    - willian.vag@gmail.com

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: transport-api-wcorrea
