CREATE TABLE centro_de_custo(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    descricao varchar(250) NOT NULL,

    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inativo BOOLEAN DEFAULT FALSE,

    classe_id BIGINT(20) NOT NULL,

    FOREIGN KEY (classe_id) REFERENCES classe(id)
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;