CREATE TABLE veiculo (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    placa VARCHAR(8) NOT NULL,
    frota VARCHAR(15) NOT NULL,

    obs TEXT,

    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;