

-- ---------------------------------------------------
-- CONTA DO BANCO
-- ---------------------------------------------------
CREATE TABLE FIN_BANCO_AGENCIA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    ID_CIDADE BIGINT(20), FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID),
    ID_BANCO BIGINT(20), FOREIGN KEY (ID_BANCO) REFERENCES BANCO(ID),

    CODIGO VARCHAR(50),
    DIGITO CHAR(1),
    NOME VARCHAR(100),
    LOGRADOURO VARCHAR(100),
    CEP VARCHAR(9),
    BAIRRO VARCHAR(100),
    TELEFONE_AGENCIA VARCHAR(20),
    GERENTE VARCHAR(100),
    TELEFONE_GERENTE VARCHAR(20),
    OBS TEXT
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;



-- ---------------------------------------------------
-- CONTA DO BANCO
-- ---------------------------------------------------
CREATE TABLE FIN_BANCO_CONTA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    ID_BANCO_AGENCIA BIGINT(20), FOREIGN KEY (ID_BANCO_AGENCIA) REFERENCES FIN_BANCO_AGENCIA(ID),

    CONTA_NUMERO VARCHAR(20),
    CONTA_DIGITO VARCHAR(1),
    NOME VARCHAR(50),
    DESCRICAO TEXT,
    TIPO VARCHAR(20),
    INATIVO BOOLEAN DEFAULT FALSE
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;



-- ---------------------------------------------------
-- PLANO DE CONTA
-- ---------------------------------------------------
CREATE TABLE FIN_PLANO_DE_CONTA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    INATIVO BOOLEAN DEFAULT FALSE
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- CHEQUE RECEBIDO
-- ---------------------------------------------------
CREATE TABLE FIN_CHEQUE_RECEBIDO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    CPF_CNPJ VARCHAR(14),
    NOME VARCHAR(100),
    CODIGO_BANCO VARCHAR(10),
    CODIGO_AGENCIA VARCHAR(10),
    CONTA VARCHAR(20),
    NUMERO INTEGER,
    DATA_EMISSAO DATE,
    BOM_PARA DATE,
    DATA_COMPENSACAO DATE,
    VALOR DECIMAL(20,2) DEFAULT 0.00,

    ID_PESSOA BIGINT(20),     FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- TIPO DE RECEBIMENTO
-- ---------------------------------------------------
CREATE TABLE FIN_TIPO_RECEBIMENTO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    INATIVO BOOLEAN DEFAULT FALSE
)
ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- FOCUMENTO DE ORIGEM
-- ---------------------------------------------------
CREATE TABLE FIN_DOCUMENTO_ORIGEM (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(100),
    DESCRICAO VARCHAR(250),
    ID_FRETAMENTO_EVENTUAL BIGINT(20),     FOREIGN KEY (ID_FRETAMENTO_EVENTUAL) REFERENCES FRETAMENTO_EVENTUAL(ID)
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- PARCELA RECEBIMENTO
-- ---------------------------------------------------
CREATE TABLE FIN_LANCAMENTO_RECEBER (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    ID_FIN_PLANO_DE_CONTA BIGINT(20),     FOREIGN KEY (ID_FIN_PLANO_DE_CONTA) REFERENCES FIN_PLANO_DE_CONTA(ID),
    ID_FIN_DOCUMENTO_ORIGEM BIGINT (20),  FOREIGN KEY (ID_FIN_DOCUMENTO_ORIGEM) REFERENCES  FIN_DOCUMENTO_ORIGEM(ID),
    ID_CLIENTE BIGINT(20), FOREIGN KEY (ID_CLIENTE) REFERENCES PESSOA(ID),
    ID_VENDEDOR BIGINT(20), FOREIGN KEY (ID_VENDEDOR) REFERENCES PESSOA(ID),
    
    QUANTIDADE_PARCELA INTEGER,
    VALOR_TOTAL DECIMAL(20,2) DEFAULT 0.00,
    VALOR_A_RECEBER DECIMAL(20,2) DEFAULT 0.00,
    DATA_LANCAMENTO DATE,
    NUMERO_DOCUMENTO VARCHAR(50),
    PRIMEIRO_VENCIMENTO DATE,
    
    COMISSAO_TAXA DECIMAL(20,2) DEFAULT 0.00,
    COMISSAO_VALOR DECIMAL(20,2) DEFAULT  0.00
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- STATUS DA PARCELA
-- ---------------------------------------------------
CREATE TABLE FIN_STATUS_PARCELA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    SITUACAO VARCHAR(2),
    DESCRICAO VARCHAR(100),
    PROCEDIMENTE TEXT,
    INATIVO BOOLEAN DEFAULT FALSE
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ---------------------------------------------------
-- PARCELA RECEBIMENTO
-- ---------------------------------------------------
CREATE TABLE FIN_PARCELA_RECEBIMENTO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    ID_FIN_TIPO_RECEBIMENTO BIGINT(20),     FOREIGN KEY (ID_FIN_TIPO_RECEBIMENTO) REFERENCES FIN_TIPO_RECEBIMENTO(ID),
    ID_FIN_CHEQUE_RECEBIDO BIGINT(20),      FOREIGN KEY (ID_FIN_CHEQUE_RECEBIDO) REFERENCES FIN_CHEQUE_RECEBIDO(ID),
    ID_FIN_BANCO_CONTA BIGINT(20),          FOREIGN KEY (ID_FIN_BANCO_CONTA) REFERENCES  FIN_BANCO_CONTA(ID),
        
    DATA_RECEBIMENTO DATE,
    TAXA_JUROS DECIMAL(20,2) DEFAULT 0.00,
    TAXA_MULTA DECIMAL(20,2) DEFAULT 0.00,
    TAXA_DESCONTO DECIMAL(20,2) DEFAULT 0.00,
    VALOR_JUROS DECIMAL(20,2) DEFAULT 0.00,
    VALOR_MULTA DECIMAL(20,2) DEFAULT 0.00,
    VALOR_DESCONTO DECIMAL(20,2) DEFAULT 0.00,
    VALOR_RECEBIDO DECIMAL(20,2) DEFAULT 0.00    
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- -
-- CABECALHO DAS PARCELAS
-- 
CREATE TABLE FIN_PARCELA_RECEBER (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    ID_FIN_LANCAMENTO_RECEBER BIGINT(20),   FOREIGN KEY (ID_FIN_LANCAMENTO_RECEBER) REFERENCES FIN_LANCAMENTO_RECEBER(ID),
    ID_FIN_STATUS_PARCELA BIGINT(20),       FOREIGN KEY (ID_FIN_STATUS_PARCELA) REFERENCES FIN_STATUS_PARCELA(ID),
    ID_FIN_BANCO_CONTA BIGINT(20),          FOREIGN KEY (ID_FIN_BANCO_CONTA) REFERENCES FIN_BANCO_CONTA(ID),
    
    NUMERO_PARCELA INTEGER,
    DATA_EMISSAO DATE,
    DATA_VENCIMENTO DATE,
    DESCOJNTO_ATE DATE,
    VALOR DECIMAL(20,2) DEFAULT 0.00,
    EMITIU_BOLETO BOOLEAN DEFAULT FALSE,
    BOLETO_NOSSO_NUMERO VARCHAR(100)

)
ENGINE = InnoDB DEFAULT CHARSET = utf8;
