CREATE TABLE FIN_NATUREZA_FINANCEIRA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    INATIVO BOOLEAN DEFAULT FALSE
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;



CREATE TABLE FIN_TIPO_RECEBIMENTO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    INATIVO BOOLEAN DEFAULT FALSE
)
ENGINE = InnoDB DEFAULT CHARSET = utf8;




CREATE TABLE FIN_PARCELA_RECEBER (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,

)
ENGINE = InnoDB DEFAULT CHARSET = utf8;





CREATE TABLE FIN_PARCELA_RECEBIMENTO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT

)
ENGINE = InnoDB DEFAULT CHARSET = utf8;


-- ------------------------------------------------------
--  Faz o cadastro de todos os recebimentos
-- ------------------------------------------------------
CREATE TABLE FIN_LANCAMENTO_RECEBER (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT

)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;
