CREATE TABLE person (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(150) NOT NULL,
    email VARCHAR(250),
    site VARCHAR(250),

    student BOOLEAN DEFAULT FALSE,
    client BOOLEAN DEFAULT FALSE,
    provider BOOLEAN DEFAULT FALSE,
    collaborator BOOLEAN DEFAULT FALSE,
    shipping_company BOOLEAN DEFAULT FALSE,
    removed BOOLEAN DEFAULT FALSE,

    date_creation  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modification_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;