CREATE TABLE pessoa (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(250) NOT NULL,
    tipo VARCHAR(150) NOT NULL,
    email VARCHAR(250),
    site VARCHAR(250),

    estudante BOOLEAN DEFAULT FALSE,
    cliente BOOLEAN DEFAULT FALSE,
    fornecedor BOOLEAN DEFAULT FALSE,
    colaborador BOOLEAN DEFAULT FALSE,
    transportadora BOOLEAN DEFAULT FALSE,
    inativo BOOLEAN DEFAULT FALSE,

    date_creation  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modification_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;